### ISSUE TITLE
Execute optimal-mrpp-continuous on Ubuntu OS?

### ISSUE THREAD

**Issue by ldg810** [rutgers-arc-lab/optimal-mrpp-continuous#2]
Hi, I am trying to execute optimal-mrpp-continuous for optimizing multi-robot path problem.

My PC environment is as follows.

- Ubuntu 16.04
- Qt 4.8.2
- All required libraries are installed. (Boost/CGAL/gmp/Gurobi/LibQGLViewer/Visilibity)

However, I failed to execute the program. (with many types of error mainly comes from linking libraries)
Did you tried the program in linux OS environment? or could you share your environment? (I guess you used Windows OS and Eclipse or Visual studio as IDE)

**Comment by arc-l** [comment]
We were able to execute in both Windows and MacOS X. In fact, the program was initially developed mainly under MacOS.
